"""
Rebuilds the Smile Arc tooth mark as clean vector shapes.

The logo on the signboard is drawn with calligraphic (tapering) strokes. Each stroke
here is a hand-traced centreline plus a width profile; the script offsets the
centreline to produce a filled outline, and also writes the centreline itself so the
hero can "draw" the mark with a mask.

Run:  python3 scripts/build-logo-paths.py
Out:  src/components/brand/mark-data.ts
"""
import numpy as np, json, pathlib

S = 0.25  # traced in a 4x enlarged view of the 211x198 logo

def catmull(points, n=200):
    P = np.array(points, float)
    P = np.vstack([P[0] - (P[1] - P[0]), P, P[-1] + (P[-1] - P[-2])])
    out = []
    for i in range(1, len(P) - 2):
        p0, p1, p2, p3 = P[i - 1], P[i], P[i + 1], P[i + 2]
        for t in np.linspace(0, 1, 24, endpoint=False):
            t2, t3 = t * t, t * t * t
            out.append(0.5 * ((2 * p1) + (-p0 + p2) * t + (2 * p0 - 5 * p1 + 4 * p2 - p3) * t2 + (-p0 + 3 * p1 - 3 * p2 + p3) * t3))
    out.append(P[-2])
    return np.array(out)

def resample(curve, n):
    d = np.r_[0, np.cumsum(np.hypot(*np.diff(curve, axis=0).T))]
    s = np.linspace(0, d[-1], n)
    return np.c_[np.interp(s, d, curve[:, 0]), np.interp(s, d, curve[:, 1])], d

def widths_along(curve_dense, ctrl_pts, ctrl_w, n):
    # arc-length position of each control point along the dense curve
    _, d = resample(curve_dense, 2)
    dd = np.r_[0, np.cumsum(np.hypot(*np.diff(curve_dense, axis=0).T))]
    pos = []
    for p in ctrl_pts:
        i = np.argmin(np.hypot(*(curve_dense - np.array(p)).T)); pos.append(dd[i])
    pos = np.array(pos); s = np.linspace(0, dd[-1], n)
    w = np.interp(s, pos, ctrl_w)
    k = 5  # light smoothing so the taper has no kinks
    w = np.convolve(np.pad(w, k, mode='edge'), np.ones(2 * k + 1) / (2 * k + 1), mode='valid')
    w[0] = ctrl_w[0]; w[-1] = ctrl_w[-1]
    return w

def outline(ctrl_pts, ctrl_w, n=110):
    dense = catmull(ctrl_pts)
    c, _ = resample(dense, n)
    w = widths_along(dense, ctrl_pts, ctrl_w, n)
    t = np.gradient(c, axis=0); t /= np.hypot(t[:, 0], t[:, 1])[:, None]
    nrm = np.c_[-t[:, 1], t[:, 0]]
    left = c + nrm * (w / 2)[:, None]; right = c - nrm * (w / 2)[:, None]
    poly = np.vstack([left, right[::-1]]) * S
    return poly, c * S

def fmt(poly):
    pts = [f"{x:.1f} {y:.1f}" for x, y in poly]
    return "M" + " L".join(pts) + "Z"

def spine(c, n=48):
    r, _ = resample(c, n)
    return "M" + " L".join(f"{x:.1f} {y:.1f}" for x, y in r)

strokes = {
 # id: (tone, points, widths)
 "crown": ("green", [(430,158),(392,140),(340,118),(285,104),(232,103),(190,122),(155,165),(132,225),(124,300),(130,380),(146,450),(172,520),(205,592),(240,638),(272,655),(303,647),(335,618),(365,572),(388,525),(425,478),(472,436)],
            [2,5,9,12,13,15,19,23,25,25,24,23,22,21,21,20,18,16,13,8,2]),
 "arc": ("green", [(315,218),(360,206),(415,182),(470,140),(530,96),(590,67),(650,52),(700,66),(728,104),(738,152),(735,215)],
            [2,6,10,13,15,18,22,26,28,28,24]),
 "swoosh": ("green", [(535,326),(580,322),(630,312),(685,295),(740,268),(790,236),(834,204)],
            [2,10,16,19,16,9,1.5]),
 "tick": ("green", [(511,294),(497,308),(491,325),(494,344),(505,352)], [1,5,8,6,1]),
 "root": ("blue", [(728,292),(720,335),(705,395),(682,455),(650,520),(612,580),(568,635),(520,681),(480,703),(452,695),(432,668),(417,622),(402,570),(388,528)],
            [20,22,24,25,25,25,24,23,22,21,20,18,16,12]),
}

items, allp = [], []
for sid, (tone, pts, w) in strokes.items():
    poly, c = outline(pts, w)
    allp.append(poly)
    items.append({"id": sid, "tone": tone, "shape": fmt(poly), "spine": spine(c)})
A = np.vstack(allp)
pad = 1.5
minx, miny = A.min(axis=0) - pad; maxx, maxy = A.max(axis=0) + pad
vb = f"{minx:.1f} {miny:.1f} {maxx-minx:.1f} {maxy-miny:.1f}"

out = pathlib.Path("src/components/brand/mark-data.ts")
out.write_text(
    "// Generated by scripts/build-logo-paths.py - do not edit by hand.\n"
    f"export const MARK_VIEWBOX = \"{vb}\";\n"
    f"export const MARK_ASPECT = {(maxx-minx)/(maxy-miny):.4f};\n"
    "export type MarkStroke = { id: string; tone: \"green\" | \"blue\"; shape: string; spine: string };\n"
    "export const MARK_STROKES: MarkStroke[] = " + json.dumps(items, indent=1) + ";\n"
)
print("viewBox", vb, "bytes", out.stat().st_size)

# Standalone SVG for favicon / public use
svg = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb}" role="img" aria-label="Smile Arc Dental Care">',
 '<defs><linearGradient id="g" gradientUnits="userSpaceOnUse" x1="200" y1="30" x2="40" y2="170"><stop offset="0" stop-color="#2A9163"/><stop offset="1" stop-color="#6FBF9E"/></linearGradient>',
 '<linearGradient id="b" gradientUnits="userSpaceOnUse" x1="180" y1="75" x2="115" y2="176"><stop offset="0" stop-color="#3A8CCB"/><stop offset="1" stop-color="#63AADF"/></linearGradient></defs>']
for it in items:
    svg.append(f'<path d="{it["shape"]}" fill="url(#{"g" if it["tone"]=="green" else "b"})"/>')
svg.append('</svg>')
pathlib.Path("public").mkdir(exist_ok=True)
pathlib.Path("public/logo-mark.svg").write_text("\n".join(svg))
pathlib.Path("src/app").mkdir(parents=True, exist_ok=True)
pathlib.Path("src/app/icon.svg").write_text("\n".join(svg))
